### ISSUE TITLE
[Composer.json] nette/di fixed on v3.0.12 version

### ISSUE THREAD

**Issue by honzavaclavik** [dek-cz/Doctrine#1]
https://github.com/dek-cz/Doctrine/blob/0cfba5f4a706c92274a0cac9ddce57aa2b682707/composer.json#L22

Please change it to: 
`"nette/di": "^3.0.12",`
or
`"nette/di": "^3.0",`

**Comment by janzarubadek** [comment]
Realized.

**Comment by honzavaclavik** [comment]
GREAT!
